project_id = "empndmpeyrdycjdesoxr"

[functions.invite-user]
verify_jwt = false

[functions.company-financials]
verify_jwt = false

[functions.vat-reliability]
verify_jwt = false

[functions.send-onboarding-summary]
verify_jwt = false
